led.enable(false)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P9, 1)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P9, 0)
    basic.pause(1000)
    music.setVolume(255)
    music.playMelody("C5 A B G A F G E ", 250)
    music.setVolume(197)
    music.playMelody("C E D F E G F A ", 203)
    music.setVolume(144)
    music.playMelody("B B B B B B B B ", 151)
    music.setVolume(255)
    music.playMelody("C5 C5 C5 C5 C5 C5 C5 C5 ", 120)
})
